### PR TITLE
DEV-14934 - Update CODEOWNERS

### PR DESCRIPTION
**Pull request by pradeepwithtamr**

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by souza-dan — COMMENTED** [review]
Before we can merge, we'll need this check to pass:
```
+ terraform fmt

Build failed! Please run terraform fmt on your branch and commit the changes

```

So we'll need to run `terraform fmt --recursive ./`

**Review by souza-dan — APPROVED** [review]

**Pull request merged**
